### ISSUE TITLE
Repeat saves break things

### ISSUE THREAD

**Issue by bessey** [bessey/vscode-rufo#3]
Leaving a note for myself and others, looks like my latest refactor broke the formatter intermittently.  Throws an undefined error to console, which is odd as every code path seems to log _something_ useful, so I must've missed a path.

**Comment by lbhtb** [comment]
Hi i have installed latest rufo in windows, it gave the following error. i am using ruby verions 1.9.3.
Can you help me in resolving this issue ?
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `r
equire': C:/Ruby193/lib/ruby/gems/1.9.1/gems/rufo-0.2.0/lib/rufo.rb:8: syntax er
ror, unexpected tPOW (SyntaxError)
  def self.format(code, **options)
                          ^
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rufo-0.2.0/lib/rufo.rb:9: syntax error, unex
pected tPOW, expecting ')'
    Formatter.format(code, **options)
                             ^
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rufo-0.2.0/lib/rufo.rb:18: syntax error, une
xpected $end, expecting keyword_end
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_requir
e.rb:55:in `require'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rufo-0.2.0/exe/rufo:2:in `<top
(required)>'
        from C:/Ruby193/bin/rufo:22:in `load'
        from C:/Ruby193/bin/rufo:22:in `<main>'
